AWSTemplateFormatVersion: "2010-09-09"
Description: "Deploys the Cluster Autoscaler helm chart into the EKS cluster"
Parameters:
  EKSSubnetIds:
    Type: List<String>
  NodeInstanceRoleName:
    Type: String
  EksClusterName:
    Type: String
  KubernetesVersion:
    Type: String
  VPCSecurityGroup:
    Type: String
Mappings:
  K8sVersionMap:
    "1.16":
      ImageTag: v1.16.5
Resources:
  ClusterAutoScalerPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: cluster-autoscaler
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - autoscaling:DescribeAutoScalingGroups
              - autoscaling:DescribeAutoScalingInstances
              - autoscaling:DescribeLaunchConfigurations
              - autoscaling:DescribeTags
            Resource: "*"
          - Effect: Allow
            Action:
              - autoscaling:SetDesiredCapacity
              - autoscaling:TerminateInstanceInAutoScalingGroup
            Resource: !Sub "arn:${AWS::Partition}:autoscaling:${AWS::Region}:${AWS::AccountId}:autoScalingGroup:*:autoScalingGroupName/*"
      Roles:
        - !Ref NodeInstanceRoleName
  AutoScalerHelmChart:
    DependsOn:
      - ClusterAutoScalerPolicy
    Type: "AWSQS::Kubernetes::Helm"
    DeletionPolicy: Retain
    Properties:
      ClusterID: !Ref EksClusterName
      Namespace: kube-system
      Chart: stable/cluster-autoscaler
      VPCConfiguration:
        SecurityGroupIds: [ !Ref VPCSecurityGroup ]
        SubnetIds: !Ref EKSSubnetIds
      Values:
        awsRegion: !Ref 'AWS::Region'
        cloudProvider: aws
        image.repository: eu.gcr.io/k8s-artifacts-prod/autoscaling/cluster-autoscaler
        image.tag: !FindInMap
          - K8sVersionMap
          - !Ref KubernetesVersion
          - ImageTag
        rbac.create: true
        rbac.pspEnabled: true
        autoDiscovery.clusterName: !Ref EksClusterName
        sslCertPath: /etc/ssl/certs/ca-bundle.crt
        extraArgs.balance-similar-node-groups: false
        extraArgs.expander: random
Outputs:
  AutoScalerReleaseName:
    Value: !Ref AutoScalerHelmChart
